-- MySQL Script generated by MySQL Workbench
-- Sun 03 Nov 2019 21:16:42 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pidb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pidb` ;

-- -----------------------------------------------------
-- Schema pidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pidb` ;
USE `pidb` ;

-- -----------------------------------------------------
-- Table `pidb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`users` ;

CREATE TABLE IF NOT EXISTS `pidb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pidb`.`recordings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`recordings` ;

CREATE TABLE IF NOT EXISTS `pidb`.`recordings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `recTime` DATETIME NOT NULL,
  `recTriggered` TINYINT NOT NULL,
  `recType` TINYINT NOT NULL,
  `recIp` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pidb`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`settings` ;

CREATE TABLE IF NOT EXISTS `pidb`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attribute` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE pidb;
LOCK TABLES `users` WRITE;
INSERT INTO `users` VALUES (1,'admin','$2y$10$LKhOqAtQmDgEwR/x1.89X.R1LRi19WbJdTYoxN7WOelsu4JjAgWO6');
UNLOCK TABLES;
LOCK TABLES `settings` WRITE;
INSERT INTO `settings` VALUES (1,'/home/pi/Pictures'),(2,'/home/pi/Videos'),(3,'/home/pi'),(4,1),(5,NULL),(6,NULL),(7,NULL),(8,NULL),(9,NULL),(10,NULL),(11,'000000000000000000000000'),(12,'000000000000000000000000'),(13,'000000000000000000000000'),(14,'000000000000000000000000'),(15,'000000000000000000000000'),(16,'000000000000000000000000'),(17,'000000000000000000000000');
UNLOCK TABLES;
