-- MySQL Script generated by MySQL Workbench
-- Fri 25 Oct 2019 22:00:44 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pidb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pidb` ;

-- -----------------------------------------------------
-- Schema pidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pidb` ;
USE `pidb` ;

-- -----------------------------------------------------
-- Table `pidb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`users` ;

CREATE TABLE IF NOT EXISTS `pidb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pidb`.`recordings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`recordings` ;

CREATE TABLE IF NOT EXISTS `pidb`.`recordings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `recTime` DATETIME NOT NULL,
  `recTriggered` TINYINT NOT NULL,
  `recType` TINYINT NOT NULL,
  `recIp` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pidb`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pidb`.`settings` ;

CREATE TABLE IF NOT EXISTS `pidb`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attribute` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
