-- MySQL Script generated by MySQL Workbench
-- Fri 25 Oct 2019 17:34:25 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pi` ;

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi` DEFAULT CHARACTER SET utf8mb4 ;
USE `pi` ;

-- -----------------------------------------------------
-- Table `pi`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi`.`users` ;

CREATE TABLE IF NOT EXISTS `pi`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `useremail` TEXT NULL,
  `ipaddr` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi`.`records` ;

CREATE TABLE IF NOT EXISTS `pi`.`records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rec_time` DATETIME NOT NULL,
  `rec_type` TINYINT NOT NULL,
  `rec_trig` TINYINT NOT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_records_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_records_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `pi`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`Settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi`.`Settings` ;

CREATE TABLE IF NOT EXISTS `pi`.`Settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memo` TEXT NULL,
  `value` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Allow remote control
-- -----------------------------------------------------
create user 'pi'@'%' identified by 'raspberry';
grant all privileges on pi*. to 'pi'@'%';
exit;
